#!/usr/bin/env node
/* ============================================================
   PRERENDER PROJECT PAGES FOR SEO / LINK PREVIEWS

   Reads data.js and writes a real static page per project at
   work/<slug>.html — served at /work/<slug>, since GitHub Pages resolves
   extensionless URLs — with the title, description, canonical URL and
   Open Graph / Twitter tags baked into the HTML.

   Why: every project used to live at project.html?id=<id>, where all the
   content is injected by main.js at runtime. Google renders JS and copes,
   but social scrapers (Slack, iMessage, LinkedIn, X, Discord) never run it —
   so every shared project link previewed as a bare "DECARLO — Project".
   Static <head> tags fix that, and give each project crawlable, unique HTML.

   The body is identical to project.html and still hydrates via main.js. The
   only difference is data-project-id on <body>, which main.js reads when
   there's no ?id= param (see projectSlug/currentProject in main.js).

   Run after editing data.js:   node build-seo.mjs
   No dependencies — plain Node.
   ============================================================ */

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(fileURLToPath(import.meta.url));

/* Canonical origin. Matches CNAME (bare domain, no www). Keep in sync with
   the canonical/og:url tags hand-written in the root-level .html files. */
const ORIGIN = "https://decarlo.design";

/* Fallback share image for projects with no usable cover. Also the default on
   the root-level pages, where it's hand-written into each <head>. Square
   (800x800), so it centre-crops in a summary_large_image card. */
const DEFAULT_OG_IMAGE = "assets/img/info/head-knot.png";

const OUT_DIR = "work";
const DESC_MAX = 155;

/* Present in every generated file. prune() uses it to tell its own output
   apart from anything hand-placed in work/ before deleting. */
const MARKER = "Generated by build-seo.mjs";

/* ---------- load SITE + PROJECTS out of data.js ----------
   data.js declares them with `const`, so they never land on the sandbox
   global. Appending an expression makes them the script's completion value. */
function loadData() {
  const code = fs.readFileSync(path.join(ROOT, "data.js"), "utf8");
  return vm.runInNewContext(`${code}\n;({ SITE, PROJECTS })`, {}, { filename: "data.js" });
}

/* ---------- text helpers ---------- */
const stripTags = (s) => String(s).replace(/<[^>]*>/g, "");

/* Flatten whitespace, and heal punctuation that only looks wrong once tags are
   gone — e.g. "for <a …>Strava.</a>." collapses to "for Strava.." */
const collapse = (s) =>
  stripTags(s)
    .replace(/\s+/g, " ")
    .replace(/\s+([,.;:!?])/g, "$1")
    .replace(/([,.;:!?])\1+/g, "$1")
    .trim();

/* Truncate on a word boundary so descriptions don't end mid-word. */
function truncate(s, max = DESC_MAX) {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const at = cut.lastIndexOf(" ");
  return `${(at > max * 0.6 ? cut.slice(0, at) : cut).replace(/[,;:.\s]+$/, "")}…`;
}

/* HTML-escape for attribute values. Project copy contains apostrophes and
   the odd ampersand, both of which would otherwise break the meta tags. */
const esc = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

/* ---------- per-project derivations ---------- */
const slugOf = (p) => String(p.id).toLowerCase(); // must match main.js projectSlug

/* Description, best source first:
     1. seoDescription — set it on a project in data.js to override
     2. the project's first sidebar paragraph (public even when private)
     3. title / tags / year
   Private projects deliberately still use the sidebar: main.js renders that
   column for them, so it is already public. Only `images`/`content` are held
   back, and those are never read here. */
function describe(p) {
  if (p.seoDescription) return collapse(p.seoDescription);

  const fromSidebar = (p.sidebar || []).find((s) => s && typeof s.text === "string" && collapse(s.text));
  if (fromSidebar) return truncate(collapse(fromSidebar.text));

  return collapse([p.title, p.tags, p.year].filter(Boolean).join(" — "));
}

/* Share image: the cover if it exists on disk, else the first real image,
   else the site default. Verified against the filesystem because a 404
   og:image renders as a blank card. Videos can't be preview images. */
function shareImage(p, warn) {
  const exists = (rel) => rel && fs.existsSync(path.join(ROOT, rel));
  const isVideo = (rel) => /\.(mp4|webm|mov)$/i.test(rel || "");

  if (exists(p.cover) && !isVideo(p.cover)) return p.cover;
  if (p.cover) warn(`cover missing or not an image (${p.cover || "unset"})`);

  const alt = (p.images || []).find((src) => typeof src === "string" && !isVideo(src) && exists(src));
  if (alt) return alt;

  warn(`no usable image, falling back to ${DEFAULT_OG_IMAGE}`);
  return DEFAULT_OG_IMAGE;
}

/* ---------- page template ---------- */
function page({ site, p, slug, desc, image }) {
  const title = `${site.name} — ${p.title}`;
  const url = `${ORIGIN}/${OUT_DIR}/${slug}`; // extensionless — GitHub Pages maps it to <slug>.html
  const imageUrl = `${ORIGIN}/${image.split("/").map(encodeURIComponent).join("/")}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Generated by build-seo.mjs from data.js — do not edit by hand. -->
  <!-- Served at /work/<slug> (no extension), so the browser resolves relative
       URLs against /work/. This rebases styles.css, data.js, main.js and every
       assets/ path back to the site root. -->
  <base href="../" />
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc)}" />
  <link rel="canonical" href="${esc(url)}" />

  <meta property="og:type" content="article" />
  <meta property="og:site_name" content="${esc(site.name)}" />
  <meta property="og:title" content="${esc(title)}" />
  <meta property="og:description" content="${esc(desc)}" />
  <meta property="og:url" content="${esc(url)}" />
  <meta property="og:image" content="${esc(imageUrl)}" />
  <meta property="og:image:alt" content="${esc(p.title)}" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${esc(title)}" />
  <meta name="twitter:description" content="${esc(desc)}" />
  <meta name="twitter:image" content="${esc(imageUrl)}" />

  <!-- Root-absolute, so <base href="../"> above doesn't rewrite them. -->
  <link rel="icon" href="/favicon.ico" sizes="32x32" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />

  <link rel="stylesheet" href="styles.css" />
</head>
<body data-page="project.html" data-project-id="${esc(p.id)}">
  <header class="topbar"></header>

  <!-- Crawlable text for scrapers that don't run JS. Invisible to everyone
       else, so it can't collide with what main.js renders below. -->
  <noscript>
    <h1>${esc(p.title)}</h1>
    <p>${esc(desc)}</p>
    <p><a href="/">${esc(site.name)}</a></p>
  </noscript>

  <div class="layout">
    <!-- LEFT: 1/4 width, quick info about this project -->
    <aside class="left" id="proj-info"></aside>

    <div class="divider" title="Drag to resize · double-click to reset"></div>

    <!-- RIGHT: 3/4 width, single project detail -->
    <main class="right">
      <article class="detail" id="detail"></article>
    </main>
  </div>

  <script src="data.js"></script>
  <script src="main.js"></script>
</body>
</html>
`;
}

/* ---------- build ---------- */
const { SITE, PROJECTS } = loadData();

/* `hidden` projects are meant to be unlisted, so they get no indexable page —
   they stay reachable at project.html?id=<id>. */
const build = PROJECTS.filter((p) => p && p.id && !p.hidden);

const seen = new Map();
let warnings = 0;

for (const p of build) {
  const slug = slugOf(p);

  if (seen.has(slug)) {
    console.error(`  !  ${slug}: slug collides with id "${seen.get(slug)}" — skipped`);
    warnings++;
    continue;
  }
  seen.set(slug, p.id);

  const warn = (msg) => {
    console.error(`  !  ${slug}: ${msg}`);
    warnings++;
  };

  const desc = describe(p);
  const image = shareImage(p, warn);

  fs.mkdirSync(path.join(ROOT, OUT_DIR), { recursive: true });
  fs.writeFileSync(path.join(ROOT, OUT_DIR, `${slug}.html`), page({ site: SITE, p, slug, desc, image }));

  console.log(`  ✓  /${OUT_DIR}/${slug}  ${p.title}`);
}

/* ---------- prune output this script no longer owns ----------
   Covers renamed ids and the earlier work/<slug>/index.html layout. Only ever
   deletes files carrying MARKER, so anything hand-written in work/ is safe. */
function prune(keep) {
  const dir = path.join(ROOT, OUT_DIR);
  if (!fs.existsSync(dir)) return [];

  const generated = (file) => {
    try {
      return fs.readFileSync(file, "utf8").includes(MARKER);
    } catch {
      return false;
    }
  };

  const gone = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      const idx = path.join(full, "index.html");
      if (fs.existsSync(idx) && generated(idx)) {
        fs.rmSync(idx);
        if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
        gone.push(`${entry.name}/index.html`);
      }
      continue;
    }

    if (entry.name.endsWith(".html") && !keep.has(entry.name) && generated(full)) {
      fs.rmSync(full);
      gone.push(entry.name);
    }
  }
  return gone;
}

const removed = prune(new Set([...seen.keys()].map((s) => `${s}.html`)));
removed.forEach((r) => console.log(`  –  ${OUT_DIR}/${r} (stale, removed)`));

console.log(`\n${seen.size} page(s) written${warnings ? `, ${warnings} warning(s)` : ""}.`);
