#!/usr/bin/env bash
# Rebuilds the favicon set from the site mark (SITE.logo in data.js).
#
#   ./tools/build-favicon.sh
#
# Outputs, all at the site root because that's where browsers look for them:
#   favicon.svg           modern browsers, scales to any size
#   favicon.ico           16 + 32px, for Safari and older browsers
#   apple-touch-icon.png  180px, iOS home screen
#
# The outputs are committed, so this only needs re-running if the mark changes.
# Requires Inkscape (brew install --cask inkscape) purely to rasterise the SVG.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="assets/img/vector/vector-head.svg"
[ -f "$SRC" ] || { echo "missing $SRC" >&2; exit 1; }
command -v inkscape >/dev/null || { echo "needs inkscape to rasterise" >&2; exit 1; }

# ---- 1. favicon.svg: the mark centred on a square white ground ----
python3 - "$SRC" <<'PY'
import io, re, sys

src = io.open(sys.argv[1], encoding="utf-8").read()
paths = re.findall(r'<path\b[^>]*/>', src)
assert paths, "no <path> found in the source mark"

box = re.search(r'viewBox="([\d.\s-]+)"', src).group(1).split()
w, h = float(box[2]), float(box[3])

# Square canvas with a little breathing room, so the cap brim doesn't touch the
# edge and look clipped. Kept deliberately tight: the mark is detailed, and at
# 16px every extra pixel of margin costs legibility faster than it buys
# separation. The mark is centred on the short axis.
PAD = 3.0
side = max(w, h) + PAD * 2
dx = PAD + (max(w, h) - w) / 2
dy = PAD + (max(w, h) - h) / 2

io.open("favicon.svg", "w", encoding="utf-8").write(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {s} {s}">\n'
    # NB: no "--" anywhere in this comment. SVG is parsed as strict XML, and a
    # double hyphen inside a comment makes the whole file ill-formed, which
    # browsers reject outright (Inkscape is lenient and will not warn you).
    '  <!-- Generated by tools/build-favicon.sh from {src}. Do not edit.\n'
    '       The mark is near-black and would vanish on a dark browser tab, so it\n'
    '       sits on a white ground (#ffffff, the site paper colour), matching how\n'
    '       the topbar renders it. -->\n'
    '  <rect width="{s}" height="{s}" fill="#ffffff"/>\n'
    '  <g transform="translate({dx} {dy})">\n{paths}\n  </g>\n'
    '</svg>\n'.format(
        s=round(side, 2), src=sys.argv[1], dx=round(dx, 2), dy=round(dy, 2),
        paths="\n".join("    " + p for p in paths),
    )
)
# Browsers parse SVG as strict XML, so an ill-formed file silently yields no
# icon at all. Fail here instead of shipping one.
import xml.dom.minidom
xml.dom.minidom.parse("favicon.svg")
print("  favicon.svg      %gx%g canvas, well-formed XML" % (round(side, 2), round(side, 2)))
PY

# ---- 2. rasterise ----
png() { inkscape favicon.svg -o "$2" -w "$1" -h "$1" >/dev/null 2>&1; }
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
png 16 "$TMP/16.png"
png 32 "$TMP/32.png"
png 180 apple-touch-icon.png
echo "  apple-touch-icon.png  180x180"

# ---- 3. favicon.ico wrapping both PNGs ----
# An .ico may hold PNG payloads rather than BMP; every browser that matters has
# supported that since IE11, and it avoids needing an encoder.
python3 - "$TMP/16.png" "$TMP/32.png" <<'PY'
import struct, sys

pngs = [(16, open(sys.argv[1], "rb").read()), (32, open(sys.argv[2], "rb").read())]

header = struct.pack("<HHH", 0, 1, len(pngs))            # reserved, type=icon, count
offset = len(header) + 16 * len(pngs)
entries, blobs = b"", b""
for size, blob in pngs:
    entries += struct.pack(
        "<BBBBHHII",
        size, size,      # width, height
        0, 0,            # palette size, reserved
        1, 32,           # colour planes, bits per pixel
        len(blob), offset,
    )
    blobs += blob
    offset += len(blob)

open("favicon.ico", "wb").write(header + entries + blobs)
print("  favicon.ico      16x16 + 32x32, %d bytes" % len(header + entries + blobs))
PY
